/**
 * prisma/seed-data/status-history.ts
 *
 * Synthesizes StatusHistory rows for each LandParcel: one row per
 * Stage the parcel passed through on its way to its current status.
 *
 * There's no research data behind these transition dates — they're
 * generated by walking the Stage enum in order and spacing synthetic
 * timestamps backward from the parcel's real `enteredStageAt`, so the
 * LAST row's changedAt always equals enteredStageAt (accurate), and
 * earlier rows are placed further back in time (synthetic).
 *
 * Usage from your main prisma/seed.ts (after landParcels exist):
 *
 *   import { seedStatusHistory } from "./seed-data/status-history";
 *   await seedStatusHistory(prisma, landParcels);
 */

import { PrismaClient, Stage } from '@prisma/client'

// Order parcels progress through — matches the Stage enum order in schema.prisma.
const STAGE_ORDER: Stage[] = [
  Stage.PROPOSAL_SUBMITTED,
  Stage.UNDER_SCRUTINY,
  Stage.NOTIFICATION_ISSUED,
  Stage.AWARD_DECLARED,
  Stage.COMPENSATION_DISBURSED,
  Stage.POSSESSION_TAKEN,
  Stage.RR_COMPLETED,
]

// Synthetic spacing between transitions, in days, when backfilling history.
const STEP_DAYS = 30

const daysBefore = (date: Date, n: number) =>
  new Date(date.getTime() - n * 24 * 60 * 60 * 1000)

interface LandParcelSeedData {
  id: string
  status: Stage
  enteredStageAt: Date
}

export async function seedStatusHistory(
  prisma: PrismaClient,
  landParcels: LandParcelSeedData[]
) {
  const statusHistoryIds: string[] = []

  // Same actor pattern as DocumentRecord.uploadedById — no per-officer
  // attribution data exists, so all synthetic transitions are attributed
  // to the seeded admin.
  const admin = await prisma.user.findFirst({
    where: { role: 'ADMIN' },
  })

  if (!admin) {
    throw new Error('Admin user not found. Seed users first.')
  }

  for (const parcel of landParcels) {
    const currentIndex = STAGE_ORDER.indexOf(parcel.status)
    const stagesSoFar = STAGE_ORDER.slice(0, currentIndex + 1)

    for (let i = 0; i < stagesSoFar.length; i++) {
      const toStage = stagesSoFar[i]
      const fromStage = i === 0 ? null : stagesSoFar[i - 1]
      const stepsBack = stagesSoFar.length - 1 - i
      const changedAt =
        stepsBack === 0
          ? parcel.enteredStageAt
          : daysBefore(parcel.enteredStageAt, stepsBack * STEP_DAYS)

      const created = await prisma.statusHistory.create({
        data: {
          parcelId: parcel.id,
          fromStage,
          toStage,
          changedById: admin.id,
          changedAt,
        },
      })
      statusHistoryIds.push(created.id)
    }
  }

  console.log(
    `Seeded ${statusHistoryIds.length} status history entries for ${landParcels.length} parcels.`
  )
  return { statusHistoryIds }
}